import type { Metadata } from "next";
import localFont from "next/font/local";
import { NextIntlClientProvider } from "@repo/i18n/client";
import type { Locale } from "@repo/i18n/config";
import { resolveLocale } from "@repo/i18n/utils";
import { getMessages } from "@repo/i18n/server";
import { cookies, headers } from "next/headers";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const headerStore = await headers();
  const locale: Locale = resolveLocale({
    locale:
      cookieStore.get("NEXT_LOCALE")?.value ?? cookieStore.get("locale")?.value,
    acceptLanguage: headerStore.get("accept-language"),
  });

  const messages = await getMessages(locale);

  return (
    <html lang={locale} dir="ltr">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
